{% set name = "nsight-compute" %}
{% set version = "2026.3.1.2" %}
{% set version_split = version.split(".")[0]+"."+version.split(".")[1]+"."+version.split(".")[2] %}
{% set cuda_version = "13.4" %}
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-sbsa" %}  # [aarch64]
{% set platform = "windows-x86_64" %}  # [win64]
{% set platform = "windows-arm64" %}  # [win and arm64]
{% set extension = "tar.xz" %}  # [not win]
{% set extension = "zip" %}  # [win]
{% set sha256 = "a0039be47cfe551f89d82087256080a9f33c6257d99a72c1164a87466ab072aa" %}  # [linux64]
{% set sha256 = "78b4913e91f3542aafd7f91ad3ae2b56bd00c81bf9c0eab130472dae97c4cf7f" %}  # [aarch64]
{% set sha256 = "b243e1b0fec34cd57d12c5c541c73c8578f56cb98ccb4caaa87cac5c435fe216" %}  # [win64]
{% set sha256 = "3708e6e60bdd1fb6d5633bd60a7563acfe0aa6a0430b51c1b2577fe85cc5cc92" %}  # [win and arm64]

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/nsight_compute/{{ platform }}/nsight_compute-{{ platform }}-{{ version }}-archive.{{ extension }}
  sha256: {{ sha256 }}

build:
  number: 0
  binary_relocation: false
  skip: true  # [osx]
  missing_dso_whitelist:
    - '*'
  runpath_whitelist:
    # Fix for "runpaths ['$ORIGIN'] found" errors
    - '$ORIGIN'  # [linux]
  overlinking_ignore_patterns:
    # Ignore 32-bit libraries for overlinking checks
    - '*linux-desktop-glibc_2_11_3-x86*'  # [linux]
requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
    - arm-variant * {{ arm_variant_type }}  # [aarch64]
    - cf-nvidia-tools 1  # [linux]
  host:
    - cuda-version {{ cuda_version }}
    - alsa-lib {{ alsa_lib }}                        # [linux]
    - dbus {{ dbus }}                                # [linux]
    - expat {{ expat }}
    # Anaconda publishes 'fontconfig' for win-arm64 platform
    - fontconfig {{ fontconfig }}
    - freetype {{ freetype }}
    - libglvnd-devel                                 # [linux]
    - libopengl-devel                                # [linux]
    - krb5 {{ krb5 }}
    - libglib {{ libglib }}
    - libxcb {{ libxcb }}                            # [linux]
    - libxkbcommon {{ libxkbcommon }}                # [linux]
    - libxkbfile {{ libxkbfile }}                    # [linux]
    - libzlib {{ libzlib }}
    - nspr {{ nspr }}                                # [linux]
    - nss {{ nss }}                                  # [linux]
    - wayland {{ wayland }}                          # [linux]
    - xcb-util-cursor {{ xcb_util_cursor }}          # [linux]
    - xcb-util-image {{ xcb_util_image }}            # [linux]
    - xcb-util-keysyms {{ xcb_util_keysyms }}        # [linux]
    - xcb-util-renderutil {{ xcb_util_renderutil }}  # [linux]
    - xcb-util-wm {{ xcb_util_wm }}                  # [linux]
    - xorg-libice {{ xorg_libice }}                  # [linux]
    - xorg-libsm {{ xorg_libsm }}                     # [linux]
    - xorg-libx11 {{ xorg_libx11 }}                  # [linux]
    - xorg-libxcomposite {{ xorg_libxcomposite }}    # [linux]
    - xorg-libxdamage {{ xorg_libxdamage }}           # [linux]
    - xorg-libxext {{ xorg_libxext }}                # [linux]
    - xorg-libxfixes {{ xorg_libxfixes }}            # [linux]
    - xorg-libxrandr {{ xorg_libxrandr }}            # [linux]
    - xorg-libxrender {{ xorg_libxrender }}          # [linux]
    - xorg-libxtst {{ xorg_libxtst }}                # [linux]
  run:
    - {{ pin_compatible("cuda-version", max_pin="x.x") }}
    - {{ pin_compatible("xorg-libxcomposite", max_pin="x.x") }}  # [linux]
    - {{ pin_compatible("xorg-libxdamage", max_pin="x.x") }}     # [linux]
    - {{ pin_compatible("xorg-libxfixes", max_pin="x.x") }}      # [linux]
    - {{ pin_compatible("xorg-libxrandr", max_pin="x.x") }}      # [linux]
    - {{ pin_compatible("xorg-libxtst", max_pin="x.x") }}        # [linux]
    - {{ pin_compatible("libxkbfile", max_pin="x.x") }}          # [linux]
  run_constrained:
    - arm-variant * {{ arm_variant_type }}  # [aarch64]

test:
  commands:
    - test -L $PREFIX/bin/ncu                                                  # [linux]
    - test -L $PREFIX/bin/ncu-ui                                               # [linux64 or aarch64]
    - if not exist %LIBRARY_PREFIX%\nsight-compute exit 1                      # [win]
    - if exist %LIBRARY_PREFIX%\nsight-compute\{{ version_split }}\lib exit 1  # [win]
    - if not exist %PREFIX%\Scripts\ncu.bat exit 1                             # [win]
    - ncu --version                                                            # [build_platform == target_platform]
    # ncu-ui test can be enabled for aarch64 once GLIBC 2.28 is made available
    # https://github.com/conda-forge/conda-forge.github.io/issues/1941
    # ncu-ui test is currently failing on linux64 as well due to missing x11 libs
    # https://github.com/conda-forge/nsight-compute-feedstock/issues/26
    # - DISPLAY=localhost:1.0 xvfb-run -a bash -c 'ncu-ui --help-all'            # [linux64]

about:
  home: https://developer.nvidia.com/nsight-compute
  license_file: LICENSE
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  license_family: Other
  summary: NVIDIA Nsight Compute is an interactive kernel profiler for CUDA applications
  description: |
    NVIDIA Nsight Compute is an interactive kernel profiler for CUDA
    applications. It provides detailed performance metrics and API
    debugging via a user interface and command line tool.
  doc_url: https://docs.nvidia.com/nsight-compute/NsightCompute/index.html
  dev_url: https://docs.nvidia.com/nsight-compute/NsightCompute/index.html

extra:
  skip-lints:
    - deprecate_license_url
  recipe-maintainers:
    - conda-forge/cuda
