{% set name = "nsight-compute" %}
{% set version = "2025.1.1.2" %}
{% set version_split = version.split(".")[0]+"."+version.split(".")[1]+"."+version.split(".")[2] %}
{% set cuda_version = "12.8" %}
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-ppc64le" %}  # [ppc64le]
{% set platform = "linux-sbsa" %}  # [aarch64]
{% set platform = "windows-x86_64" %}  # [win]
{% set extension = "tar.xz" %}  # [not win]
{% set extension = "zip" %}  # [win]

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/nsight_compute/{{ platform }}/nsight_compute-{{ platform }}-{{ version }}-archive.{{ extension }}
  sha256: 6f55f6dfb33abe15b25a5f0c656ae8d9b6a6f33e55f0337b9b6a017daf8ad610  # [linux64]
  sha256: 6070766fda9094b8556208e76140420d80f2759a49dd76f9ace15a580059226f  # [aarch64]
  sha256: 8135505c2e4a055cb9e663316003d6ab8ae5ea44641e86f5be83ff03b03f3db4  # [win]

build:
  number: 1
  binary_relocation: false
  skip: true  # [osx or ppc64le]
  missing_dso_whitelist:
    - '*'
  # The issue with LIEF: ValueError: 1879047926 is not a valid TAG
  overlinking_ignore_patterns:  # [linux]
    - "bin/ncu*"                # [linux]
    - "nsight-compute-*/**"     # [linux]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
    - arm-variant * {{ arm_variant_type }}  # [aarch64]
    - cf-nvidia-tools 1  # [linux]
  host:
    - cuda-version {{ cuda_version }}
    - alsa-lib {{ alsa_lib }}  # [linux]
    - dbus {{ dbus }}      # [linux]
    - expat {{ expat }}
    - fontconfig {{ fontconfig }}
    - freetype {{ freetype }}
    - libglvnd-devel {{ libglvnd }}       # [linux]
    - libopengl-devel {{ libopengl }}      # [linux]
    - libkrb5 {{ krb5 }}
    - libglib {{ libglib }}
    - libxcb {{ libxcb }}      # [linux]
    - libxkbcommon {{ libxkbcommon }} # [linux]
    - libxkbfile {{ libxkbfile }}     # [linux]
    - zlib {{ zlib }}
    - nspr {{ nspr }}      # [linux]
    - nss {{ nss }}        # [linux]
    - wayland {{ wayland }} # [linux]
    - xcb-util-cursor {{ xcb_util_cursor }}      # [linux]
    - xcb-util-image {{ xcb_util_image }}        # [linux]
    - xcb-util-keysyms {{ xcb_util_keysyms }}    # [linux]
    - xcb-util-renderutil {{ xcb_util_renderutil }} # [linux]
    - xcb-util-wm {{ xcb_util_wm }}              # [linux]
    - xorg-libice {{ xorg_libice }}          # [linux]
    - xorg-libsm {{ xorg_libsm }}            # [linux]
    - xorg-libx11 {{ xorg_libx11 }}          # [linux]
    - xorg-libxcomposite {{ xorg_libxcomposite }} # [linux]
    - xorg-libxdamage {{ xorg_libxdamage }}  # [linux]
    - xorg-libxext {{ xorg_libxext }}        # [linux]
    - xorg-libxfixes {{ xorg_libxfixes }}    # [linux]
    - xorg-libxrandr {{ xorg_libxrandr }}    # [linux]
    - xorg-libxrender {{ xorg_libxrender }}  # [linux]
    - xorg-libxtst {{ xorg_libxtst }}        # [linux]
  run:
    - {{ pin_compatible("cuda-version", max_pin="x.x") }}
  run_constrained:
    - arm-variant * {{ arm_variant_type }}  # [aarch64]

test:
  requires:
    # OpenGL libraries for ncu-ui GUI testing (may still have limitations in headless environments)
    - libglvnd-devel {{ libglvnd }}       # [linux]
    - libopengl-devel {{ libopengl }}      # [linux]
  commands:
    # Enable printing command execution on Windows
    - echo ON  # [win]                                             # [linux64 or aarch64]
    
    # Test main installation directory exists
    - test -d $PREFIX/nsight-compute-{{ version_split }}                       # [linux]
    
    # Test main executables exist
    - test -f $PREFIX/nsight-compute-{{ version_split }}/ncu                   # [linux]
    - test -f $PREFIX/nsight-compute-{{ version_split }}/ncu-ui                # [linux64 or aarch64]
    
    # Test target directory structure (Linux)
    - test -d $PREFIX/nsight-compute-{{ version_split }}/target                # [linux]
    
    # Test some essential shared libraries exist (Linux)
    - find $PREFIX/nsight-compute-{{ version_split }} -name "*.so" | head -1   # [linux]
    
    # Test functional execution
    - ncu --version                                                            # [build_platform == target_platform]
    - ncu --help | grep -i "NVIDIA"                                            # [build_platform == target_platform and linux]
    
    # Test ncu-ui with graceful failure handling for OpenGL issues
    - DISPLAY=localhost:1.0 xvfb-run -a bash -c 'timeout 30s ncu-ui --help-all || echo "ncu-ui test completed with expected GUI limitations"'  # [linux64]
    
    # Windows tests
    - if not exist %LIBRARY_PREFIX%\nsight-compute exit 1                      # [win]
    - if exist %LIBRARY_PREFIX%\nsight-compute\{{ version_split }}\lib exit 1  # [win]
    - if not exist %PREFIX%\Scripts\ncu.bat exit 1                             # [win]
    - if not exist %PREFIX%\Scripts\ncu-ui.bat exit 1                          # [win]
    
    # Test Windows executables exist
    - if not exist %LIBRARY_PREFIX%\nsight-compute\{{ version_split }}\ncu.exe exit 1        # [win]
    - if not exist %LIBRARY_PREFIX%\nsight-compute\{{ version_split }}\ncu-ui.exe exit 1     # [win]
    
    # Test Windows DLLs exist
    - dir %LIBRARY_PREFIX%\nsight-compute\{{ version_split }} | findstr /i "\.dll"           # [win]

about:
  home: https://developer.nvidia.com/nsight-compute
  license_file: LICENSE
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: NVIDIA Nsight Compute is an interactive kernel profiler for CUDA applications
  description: |
    NVIDIA Nsight Compute is an interactive kernel profiler for CUDA
    applications. It provides detailed performance metrics and API
    debugging via a user interface and command line tool.
  doc_url: https://docs.nvidia.com/nsight-compute/NsightCompute/index.html

extra:
  recipe-maintainers:
    - conda-forge/cuda
